### ISSUE TITLE
v6.0.3 is Broken on iOS

### ISSUE THREAD

**Issue by rzagelow** [apptentive/apptentive-flutter#30]
Out of the box iOS crashes our app with the latest version v6.0.3. And no flutter code you can add will stop this crash. The only fix I can find is adding this swift line of code: `Apptentive.shared.theme = .none;` which stops crashing your app but when the love dialog is show in dark mode it looks totally broken (like from the line of code that fixed the crash). This is basically unusable.

<img width="413" alt="Screen Shot 2022-12-09 at 5 12 54 PM" src="https://user-images.githubusercontent.com/7141163/206821864-382d23ff-10ec-4dc8-97c1-89150391d176.png">

**Comment by CaseyApptentive** [comment]
Hi @rzagelow, sorry that you're having issues. Working on an answer for you with my team. We'll follow up asap.

**Comment by NickalasB** [comment]
Hi @CaseyApptentive. The update in v6.1.1 fixes the issue for us. I believe this can be closed. Thank you for all the help
